In [4]:
import torch
 
# 定义模型 三层卷积 一层全连接
class xavierNet(torch.nn.Module):
    def __init__(self):
        super(xavierNet, self).__init__()
        self.conv1 = torch.nn.Conv2d(1, 1, 3)
        print('random init:', self.conv1.weight)
        '''
            xavier 初始化方法中服从均匀分布 U(−a,a) ，分布的参数 a = gain * sqrt(6/fan_in+fan_out)，
            这里有一个 gain，增益的大小是依据激活函数类型来设定,该初始化方法，也称为 Glorot initialization
        '''
        torch.nn.init.xavier_uniform_(self.conv1.weight, gain=1)
        print('xavier_uniform_:', self.conv1.weight)
        '''
            xavier 初始化方法中服从正态分布，
            mean=0,std = gain * sqrt(2/fan_in + fan_out)
        '''
        torch.nn.init.xavier_normal_(self.conv1.weight, gain=1)
        print('xavier_uniform_:', self.conv1.weight)
        
# 定义模型 三层卷积 一层全连接
class heNet(torch.nn.Module):
    def __init__(self):
        super(heNet, self).__init__()
        self.conv1 = torch.nn.Conv2d(1, 1, 3)
        print('random init:', self.conv1.weight)
        '''
            此为均匀分布，U~(-bound,bound)，bound=sqrt(6/(1+a^2)*fan_in)
            其中，a为激活函数的负半轴的斜率，relu是0
            mode- 可选为fan_in或fan_out,fan_in使用正向传播，方差一致；fan_out使反向传播时，方差一致nonlinearity-可选relu和leaky_relu，默认值为：leaky_relu
        '''
        torch.nn.init.kaiming_uniform(self.conv1.weight, mode='fan_in', nonlinearity='relu')
        print('kaiming_uniform:', self.conv1.weight)
        '''
            此为0均值的正态分布，N~(0,std),
            其中std=sqrt(2/(1+a^2)*fan_in)其中，a为激活函数的负半轴的斜率，relu是0
            mode- 可选为fan_in或fan_out,fan_in使正向传播时，方差一致；fan_out使反向传播时，方差一致。nonlinearity-可选relu和leaky_relu，默认值为leaky_relu.
        '''
        torch.nn.init.kaiming_normal_(self.conv1.weight, mode='fan_in', nonlinearity='relu')
        print('kaiming_normal_:', self.conv1.weight)
 
# 均匀分布初始化 使值服从均匀分布U(a,b)
# torch.nn.init.uniform_(tensor,a=0,b=1)

# 正态分布初始化，使值服从正态分布N(mean,std)，默认值为0，1
# torch.nn.init.normal_(tensor,mean=0,std=1)

# 常数初始化，值为常数val nn.init.constant_(w,0.3)
# torch.nn.init.constant_(tensor,val)

# 单位矩阵初始化，将二维tensor初始化为单位矩阵
# torch.nn.init.eye_(tensor)

# 正交初始化，使得tensor是正交的
# torch.nn.init.orthogonal_(tensor,gain=1)

# 稀疏初始化，从正态分布N~(0,std)中进行稀疏化，使每一个column有一部分为0,sparsity-每一个column稀疏的比例，即为0的比例
# torch.nn.init.sparse_(tensor,sparsity,std=0.01)
# **nn.init.sparse_(w,sparsity=0.1)

# 计算增益
# torch.nn.init.calculate_gain(nonlinearity,param=None)



 
if __name__ == '__main__':
    xavierNet = xavierNet()
    heNet = heNet()

random init: Parameter containing:
tensor([[[[ 0.1491, -0.2435,  0.2405],
          [-0.1770, -0.1404,  0.0292],
          [-0.3287,  0.1028,  0.2808]]]], requires_grad=True)
xavier_uniform_: Parameter containing:
tensor([[[[ 0.0317, -0.3468,  0.5611],
          [-0.4785, -0.3788,  0.4853],
          [-0.1947, -0.4551,  0.5619]]]], requires_grad=True)
xavier_uniform_: Parameter containing:
tensor([[[[-0.0432,  0.1933, -0.0889],
          [ 0.0144, -0.0824,  0.2355],
          [-0.3339, -0.2083,  0.0883]]]], requires_grad=True)
random init: Parameter containing:
tensor([[[[-0.2562, -0.0785,  0.3211],
          [ 0.0122,  0.2035,  0.1895],
          [-0.2908,  0.2450,  0.2278]]]], requires_grad=True)
kaiming_uniform: Parameter containing:
tensor([[[[-0.4293,  0.4197,  0.6153],
          [-0.2805, -0.5763, -0.5364],
          [-0.7412,  0.7470, -0.1140]]]], requires_grad=True)
kaiming_normal_: Parameter containing:
tensor([[[[ 0.6734, -0.1740, -0.3378],
          [-0.6837,  0.1634,  0.196

/tmp/ipykernel_3857592/2137528638.py:33: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  torch.nn.init.kaiming_uniform(self.conv1.weight, mode='fan_in', nonlinearity='relu')
